# Numpy Tutorial

In [1]:
import numpy as np

In [2]:
#arrays in numpy
a=np.array([1,2,23,3],dtype='int64')
b=np.array([1,2,23,3],dtype='int32')
print(a)
print(b)

[ 1  2 23  3]
[ 1  2 23  3]


# dtype

if data type is 
int32-Processing of data is less fast but with
int64-Processing of data is much faster than int32

In [3]:
#testing to see data processing speed of int32 and int64
print('For a:')
print(a.size)
print(a.itemsize)
print('')
print('For b:')
print(b.size)
print(b.itemsize)

For a:
4
8

For b:
4
4


# Number of dimensions Of Arrays

In [4]:
a=np.array([[2,32,3]])
print(a.ndim)

2



# Structure of Arrays

In [5]:
a=np.array([[2,31,45],[12,4,5]])
print(a)
print('Shape:'+str(a.shape))

[[ 2 31 45]
 [12  4  5]]
Shape:(2, 3)


In [6]:
#Changing the structure of the array
b=a.reshape(3,2)
print(b)

[[ 2 31]
 [45 12]
 [ 4  5]]


# Accessing & Changing specific elements,row,column etc

In [7]:
a=np.array([[2,3,21,12,4],[23,32,34,4,32]],dtype=int)
print(a)
print('')
print(a[1,1])

[[ 2  3 21 12  4]
 [23 32 34  4 32]]

32


In [8]:
#selecting rows
print(a[1,:])

[23 32 34  4 32]


In [9]:
#selecting columns
print(a[:,1])

[ 3 32]


In [10]:
#getting a fancy
print(a[0,0:-1:2])

[ 2 21]


In [11]:
#Changing values in the array
a[0,:2]=[12,16]
print(a)

[[12 16 21 12  4]
 [23 32 34  4 32]]


In [12]:
#getting specific values outside in
d=np.array([[[2,3,4],[23,26,4]]])
print(d[0,1,1])

26


# Initializing different kinds of Arrays

In [13]:
#ones
a=np.ones((2,3),dtype=int)
print(a)

[[1 1 1]
 [1 1 1]]


In [14]:
# np.arange(start,end,step,datatype)
c=np.arange(1,10,2,dtype=int)
print(c)

[1 3 5 7 9]


In [15]:
 #np.random.randint(start,end,size=(dimension)
    #getting random integers
r=np.random.randint(1,20)
print(r)

15


In [16]:
#random integer array
s=np.random.randint(1,20,size=(2,3))
print(s)

[[ 3 15 11]
 [17 19  5]]


In [17]:
#random floats array
k=np.empty((2,3))
print(k)

[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
#Zeros array
p=np.zeros((3,2),dtype=int)
print(p)

[[0 0]
 [0 0]
 [0 0]]


In [19]:
#Creating repeated array values
h=np.full((3,3),2)
print(h)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [20]:
#Creatign repeated values using another arrays shape
j=np.full_like(p,2);
print(j)
#or
print('or')
f=np.full(p.shape,3)
print(f)

[[2 2]
 [2 2]
 [2 2]]
or
[[3 3]
 [3 3]
 [3 3]]


In [21]:
#checking for the identity element of an array
i=np.identity(3,dtype=int)
print(i)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [22]:
#numpy.linspace(start, stop, num, endpoint, retstep, dtype)
#endpoint-True by default, hence the stop value is included in the sequence. If false, it is not included
#retstep-If true, returns samples and step between the consecutive numbers

fg=np.linspace(0,2,9,endpoint=True,retstep=True,dtype=int)
print(fg)

(array([0, 0, 0, 0, 1, 1, 1, 1, 2]), 0.25)


# SOME TEST

In [23]:
o=np.ones((5,5),dtype=int)
o[1:-1,1:-1]=np.zeros((3,3))
o[2,2]=9
print(o)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# Mathematical Operations 

In [24]:
a=np.array([[2,13,12],[12,4,55]])
b=np.array([[21,1,53],[1,12,5]])
print(a)

[[ 2 13 12]
 [12  4 55]]


In [25]:
#Minimum columns value
c=a.min(axis=0)
print(c)

#Minimum of rows
k=a.min(axis=1)
print(k)

[ 2  4 12]
[2 4]


In [26]:
#adding all values in array
s=a.sum();
print(s)

98


In [27]:
#Getting the square of each elements of the array
d=np.sqrt(a)
print(d)

[[1.41421356 3.60555128 3.46410162]
 [3.46410162 2.         7.41619849]]


In [28]:
#Adding each corresponfing elements of two arrays
g=a+b
print(g)

[[23 14 65]
 [13 16 60]]


In [29]:
#Multipling corresponding elements of two arrays
h=a*b
print(h)

[[ 42  13 636]
 [ 12  48 275]]


In [30]:
#Subtracting corresponding elements of two arrays
h=a-b
print(h)

[[-19  12 -41]
 [ 11  -8  50]]


In [31]:
#Using scaler on matrix
g=2*a
print(g)

[[  4  26  24]
 [ 24   8 110]]


In [32]:
#Finding the product of two matrices
a=np.array([[2,3],[3,7]])
b=np.array([[1,2],[1,17]])
print(b.dot(a))
#or
print('or')
np.matmul(b,a)

[[  8  17]
 [ 53 122]]
or


array([[  8,  17],
       [ 53, 122]])

In [33]:
#Finding the determinant of matrix
g=np.array([[3,2],[2,5]],dtype=int)
print(round(np.linalg.det(g)))

11


# Joining two arrays

In [34]:
#Joining two arrays by column joining
a=np.array([1,1,1])
b=np.array([2,2,2])
print(np.vstack((b,a)))

[[2 2 2]
 [1 1 1]]


In [35]:
#Joining two arrays by row joining
print(np.hstack((b,a)))

[2 2 2 1 1 1]


# Working with booleans in an array

In [36]:
#returning a true or false
kp=np.array([[12,3,22,12],[14,23,4,21]])
print(kp>12)

[[False False  True False]
 [ True  True False  True]]


In [37]:
#converting the true or false to the actual values
res=kp[kp>12]
print(res)

[22 14 23 21]


# Loading Data From FIle In Numpy

In [38]:
print('End')

End
